name: pre-commit

on:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: install black
        run: |
          pip install black==22.3.0

      - name: Run pre-commit
        uses: autowarefoundation/autoware-github-actions/pre-commit@main
        with:
          pre-commit-config: .pre-commit-config.yaml
